# Generated by Django 5.0.1 on 2025-06-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_session_duration_session_mode_session_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
