# Generated by Django 5.2.3 on 2025-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_bio_teacher_documents_teacher_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='documents',
            field=models.FileField(blank=True, upload_to='teachers/documents/'),
        ),
    ]
